DjangoProject/urls.py
from django.contrib import admin
from django.urls import path

from app01.views import view, depart, user, pretty, admin, account, task

urlpatterns = [
    path('', view.index),

    ######### 部門 ###########
    path('depart/list/', depart.depart_list),
    path('depart/add/', depart.depart_add),
    path('depart/del/', depart.depart_del),
    path('depart/edit/<int:id>/', depart.depart_edit),

    ######### user ###########
    path('user/list/', user.user_list),
    path('user/add/', user.user_add),
    path('user/model/form/add/', user.user_model_form_add),
    path('user/edit/<int:id>', user.user_edit),
    path('user/del/<int:id>', user.user_del),

    ########## pretty ###########
    path('pretty/list/', pretty.pretty_list),
    path('pretty/add/', pretty.pretty_add),
    path('pretty/edit/<int:id>', pretty.pretty_edit),

    # 管理員管理
    path('admin/list/', admin.admin_list),
    path('admin/add/', admin.admin_add),
    path('admin/edit/<int:id>', admin.admin_edit),
    path('admin/del/<int:id>', admin.admin_del),
    path('admin/reset/<int:id>', admin.admin_reset),

    # 登入
    path('login/', account.login),
    path('logout/', account.logout),
    path('image/code/', account.image_code),

    # 任務管理
    path('task/list/', task.task_list),
    path('task/ajax/', task.task_ajax),
    path('task/add/', task.task_add),
]

app01/models.py
from django.db import models

# Create your models here.

class DepartMent(models.Model):
    """ 部門資料 """
    title = models.CharField(verbose_name='標題', max_length=32)

    def __str__(self):
        return self.title

class UserInfo(models.Model):
    """ 員工表 """
    name = models.CharField(verbose_name="姓名", max_length=16)
    password = models.CharField(verbose_name="密碼", max_length=64)
    age = models.IntegerField(verbose_name="年齡")
    account = models.DecimalField(verbose_name="帳戶餘額", max_digits=10, decimal_places=2, default=0)
    create_time = models.DateField(verbose_name="創建時間")
    gender_choices = (
        (1, "男"),
        (2, "女")
    )
    gender = models.SmallIntegerField(verbose_name="性別", choices=gender_choices)
    # 約束
    # on_delete=models.CASCADE() 表示如果連接鍵那個資料庫的那行被刪掉，關聯的也會被刪掉
    # null=True,blank=True, on_delete=SET_NULL 表示如果連接鍵那個資料庫的那行被刪掉，關聯的變成NULL
    depart = models.ForeignKey(verbose_name="部門", to="DepartMent", to_field="id", on_delete=models.CASCADE)


class PrettyNum(models.Model):
    """ 手機號碼表 """
    mobile = models.CharField(verbose_name="手機號", max_length=10)
    price = models.IntegerField(verbose_name="價格", default=0)
    level_choices = (
        (1, "1級"),
        (2, "2級"),
        (3, "3級"),
        (4, "4級"),
    )
    level = models.SmallIntegerField(verbose_name="級別", choices=level_choices, default=1)
    status_choices = (
        (1, "已占用"),
        (2, "未使用")
    )
    status = models.SmallIntegerField(verbose_name="狀態", choices=status_choices, default=2)

class Admin(models.Model):
    username = models.CharField(verbose_name="用戶名", max_length=32)
    password = models.CharField(verbose_name="密碼", max_length=64)

    def __str__(self):
        return self.username

class Task(models.Model):
    level_choices = (
        (1, '緊急'),
        (2, '重要'),
        (3, '臨時'),
    )
    level = models.SmallIntegerField(verbose_name="級別", choices=level_choices, default=1)
    title = models.CharField(verbose_name="標題", max_length=64)
    detail = models.TextField(verbose_name="詳細訊息")
    user = models.ForeignKey(verbose_name="負責人", to="Admin", on_delete=models.CASCADE)

app01/views/account.py
from io import BytesIO

from django import forms
from django.http import HttpResponse
from django.shortcuts import render, redirect

from app01 import models
from app01.utils.bootstrap import BootStrapForm
from app01.utils.code import check_code
from app01.utils.encrypt import md5


class LoginForm(BootStrapForm):
    username = forms.CharField(
        label="用戶名",
        widget=forms.TextInput(),
        required=True
    )
    password = forms.CharField(
        label="密碼",
        widget=forms.PasswordInput(render_value=True),
        required=True
    )
    code = forms.CharField(
        label="驗證碼",
        widget=forms.TextInput,
        required=True
    )
    def clean_password(self):
        pwd = self.cleaned_data.get("password")
        return md5(pwd)

def login(request):
    if request.method == 'GET':
        form = LoginForm()
        return render(request, 'login.html', {'form': form})
    form = LoginForm(data=request.POST)
    if form.is_valid():
        user_input_code = form.cleaned_data.pop('code')
        code = request.session.get("image_code", "")
        if code.upper() != user_input_code:
            form.add_error('code', '驗證碼錯誤')
            return render(request, 'login.html', {'form': form})
        admin_object = models.Admin.objects.filter(**form.cleaned_data).first()
        if not admin_object:
            form.add_error('password', '用戶名或密碼錯誤')
            return render(request, 'login.html', {'form': form})
        request.session['info'] = {'id': admin_object.id, 'name': admin_object.username}
        request.session.set_expiry(60 * 60 * 24 * 7)
        return redirect('/admin/list/')
    return render(request, 'login.html', {'form': form})

def image_code(request):
    img, code_str = check_code()
    print(code_str)
    request.session['image_code'] = code_str
    # 給session設置60秒超時
    request.session.set_expiry(60)
    # 寫入內存(BytesIO)
    stream = BytesIO()
    img.save(stream, 'png')
    return HttpResponse(stream.getvalue())

def logout(request):
    request.session.clear()
    return redirect('/login/')

app01/views/admin.py
from django.shortcuts import render, redirect

from app01 import models
from app01.utils.form import AdminModelForm, AdminEditModelForm, AdminResetModelForm
from app01.utils.pagination import Pagination


def admin_list(request):
    data_dict = {}
    search_data = request.GET.get("q")
    if search_data:
        data_dict["username__contains"] = search_data
    queryset = models.Admin.objects.filter(**data_dict)
    page_object = Pagination(request, queryset)
    context = {
        'search_data': search_data,
        'queryset': page_object.page_queryset,
        'page_string': page_object.html()
    }
    return render(request, 'admin_list.html', context)


def admin_add(request):
    title = "新建管理員"
    if request.method == "GET":
        form = AdminModelForm()
        return render(request, 'change.html', {'form': form, 'title': title})
    form = AdminModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect('/admin/list/')
    return render(request, 'change.html', {'form': form, 'title': title})

def admin_edit(request, id):
    row_object = models.Admin.objects.filter(id=id).first()
    if not row_object:
        return render(request, 'error.html', {'msg': "數據不存在"})
    title = "編輯管理員"
    if request.method == 'GET':
        form = AdminEditModelForm(instance=row_object)
        return render(request, 'change.html', {'form': form, 'title': title})
    form = AdminEditModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect('/admin/list/')
    return render(request, 'change.html', {'form': form, 'title': title})


def admin_del(request, id):
    models.Admin.objects.filter(id=id).delete()
    return redirect('/admin/list/')

def admin_reset(request, id):
    row_object = models.Admin.objects.filter(id=id).first()
    if not row_object:
        return redirect('/admin/list/')
    title = "重置密碼 - {}".format(row_object.username)
    if request.method == 'GET':
        form = AdminResetModelForm()
        return render(request, 'change.html', {'form': form, 'title': title})
    form = AdminResetModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect('/admin/list/')
    return render(request, 'change.html', {'form': form, 'title': title})

app01/views/depart.py
from django.shortcuts import render, redirect

from app01 import models


def depart_list(request):
    depart_list = models.DepartMent.objects.all()
    return render(request, 'depart_list.html', {'depart_list': depart_list})

def depart_add(request):
    if request.method == "GET":
        return render(request, 'depart_add.html')
    title = request.POST.get('title')
    models.DepartMent.objects.create(title=title)
    return redirect('/depart/list/')

def depart_del(request):
    id = request.GET.get('id')
    models.DepartMent.objects.filter(id=id).delete()
    return redirect('/depart/list/')

def depart_edit(request, id):
    print('adsf')
    if request.method == "GET":
        title = models.DepartMent.objects.filter(id=id).first().title
        return render(request, 'depart_edit.html', {"title": title})
    title = request.POST.get('title')
    models.DepartMent.objects.filter(id=id).update(title=title)
    return redirect('/depart/list/')

app01/views/pretty.py
from django.shortcuts import render, redirect

from app01 import models
from app01.utils.form import PrettyModelForm, PrettyEditModelForm
from app01.utils.pagination import Pagination


def pretty_list(request):
    search_data = request.GET.get("q")
    data_dict = {}
    if search_data:
        data_dict['mobile__contains'] = search_data
    queryset = models.PrettyNum.objects.filter(**data_dict).order_by('-level')
    page_object = Pagination(request, queryset)
    context = {
        'queryset': page_object.page_queryset,
        'search_data': search_data,
        'page_string': page_object.html()
    }
    return render(request, 'pretty_list.html', context)

def pretty_add(request):
    if request.method == "GET":
        form = PrettyModelForm()
        return render(request, 'pretty_add.html', {'form': form})
    form = PrettyModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect('/pretty/list/')
    return render(request, 'pretty_add.html', {'form': form})

def pretty_edit(request, id):
    row_object = models.PrettyNum.objects.filter(id=id).first()
    if request.method == 'GET':
        form = PrettyEditModelForm(instance=row_object)
        return render(request, 'pretty_edit.html', {'form': form})
    form = PrettyModelForm(instance=row_object, data=request.POST)
    if form.is_valid():
        form.save()
        return redirect('/pretty/list/')
    return render(request, 'pretty_edit.html', {'form': form})

app01/views/task.py
import json

from django import forms
from django.http import HttpResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt

from app01 import models
from app01.utils.bootstrap import BootStrapModelForm


class TaskModelForm(BootStrapModelForm):
    class Meta:
        model = models.Task
        fields = "__all__"
        widgets = {
            "detail": forms.TextInput
        }


def task_list(request):
    form = TaskModelForm()
    return render(request, 'task_list.html', {'form': form})


@csrf_exempt
def task_ajax(request):
    print(request.POST)
    data_dict = {'status': True, 'data': ['11', '22', '33', '44']}
    return HttpResponse(json.dumps(data_dict))

@csrf_exempt
def task_add(request):
    print(request.POST)
    form = TaskModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        data_dict = {'status': True}
        return HttpResponse(json.dumps(data_dict))
    data_dict = {'status': False, 'error': form.errors}
    return HttpResponse(json.dumps(data_dict, ensure_ascii=False))

app01/views/user.py
from django.shortcuts import render, redirect

from app01 import models
from app01.utils.form import UserModelForm


def user_list(request):
    user_list = models.UserInfo.objects.all()
    return render(request, 'user_list.html', {'user_list': user_list})

def user_add(request):
    if request.method == 'GET':
        context = {
            'gender_choices': models.UserInfo.gender_choices,
            'depart_list': models.DepartMent.objects.all()
        }
        return render(request, 'user_add.html', context)
    username = request.POST.get('name')
    password = request.POST.get('password')
    age = request.POST.get('age')
    account = request.POST.get('account')
    time = request.POST.get('time')
    gender = request.POST.get('gender')
    depart = request.POST.get('depart')
    models.UserInfo.objects.create(name=username, password=password, age=age, account=account, create_time=time,
                                   gender=gender, depart_id=depart)
    return redirect('/user/list/')

def user_model_form_add(request):
    if request.method == "GET":
        form = UserModelForm
        return render(request, 'user_model_form_add.html', {'form': form})
    form = UserModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect('/user/list/')
    else:
        return render(request, 'user_model_form_add.html', {'form': form})

def user_edit(request, id):
    row_object = models.UserInfo.objects.filter(id=id).first()
    if request.method == "GET":
        form = UserModelForm(instance=row_object)
        return render(request, 'user_edit.html', {'form': form})
    form = UserModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect('/user/list/')
    else:
        return render(request, 'user_edit.html', {'form': form})

def user_del(request, id):
    models.UserInfo.objects.filter(id=id).delete()
    return redirect('/user/list/')

app01/views/view.py
from django.http import HttpResponse
from django.shortcuts import render


def index(request):
    return render(request, 'layout.html')

app01/templates/admin_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div style="margin-bottom: 10px" class="clearfix">
            <a class="btn btn-success" href="/admin/add/">
                <span class="glyphicon glyphicon-circle-arrow-right" aria-hidden="true"></span>
                新建管理員
            </a>
            <div style="float: right;width: 300px">
                <form method="get">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="Search for..."
                               value="{{ search_data }}">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="submit">
                                <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                            </button>
                        </span>
                    </div>
                </form>
            </div>
        </div>
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                管理員列表
            </div>

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>用戶名</th>
                    <th>密碼</th>
                    <th>重置密碼</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for user in queryset %}
                    <tr>
                        <th>{{ user.id }}</th>
                        <td>{{ user.username }}</td>
                        <td>********</td>
                        <td>
                            <a href="/admin/reset/{{ user.id }}">重置密碼</a>
                        </td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="/admin/edit/{{ user.id }}">編輯</a>
                            <a class="btn btn-danger btn-xs" href="/admin/del/{{ user.id }}">刪除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="clearfix">
            <ul class="pagination">
                {{ page_string }}

            </ul>
        </div>
    </div>
{% endblock %}

app01/templates/change.html
{% extends 'layout.html' %}

{% block content %}
<div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">{{ title }}</h3>
            </div>
            <div class="panel-body">
                {#                套版：https://v3.bootcss.com/css/#forms#}
                <form method="post" novalidate>
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color: red">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-default">提 交</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

app01/templates/depart_add.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">新建部門</h3>
            </div>
            <div class="panel-body">
                {#                套版：https://v3.bootcss.com/css/#forms#}
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>title</label>
                        <input type="text" class="form-control" placeholder="title" name="title">
                    </div>
                    <button type="submit" class="btn btn-default">提 交</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

app01/templates/depart_edit.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">修改部門</h3>
            </div>
            <div class="panel-body">
                {#                套版：https://v3.bootcss.com/css/#forms#}
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>title</label>
                        <input type="text" class="form-control" placeholder="title" name="title" value="{{ title }}">
                    </div>
                    <button type="submit" class="btn btn-default">提 交</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

app01/templates/depart_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div style="margin-bottom: 10px">
            <a class="btn btn-success" href="/depart/add/">
                <span class="glyphicon glyphicon-circle-arrow-right" aria-hidden="true"></span>
                新建部門
            </a>
        </div>
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                部門列表
            </div>

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>部門名稱</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for depart in depart_list %}
                    <tr>
                        <th>{{ depart.id }}</th>
                        <td>{{ depart.title }}</td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="/depart/edit/{{ depart.id }}/">編輯</a>
                            <a class="btn btn-danger btn-xs" href="/depart/del/?id={{ depart.id }}">刪除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

app01/templates/error.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div class="alert alert-danger" role="alert">{{ msg }}</div>
    </div>
{% endblock %}

app01/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'bootstrap-3.4.1/dist/css/bootstrap.min.css' %}">
    <style>
        .account {
            width: 400px;
            border: 1px solid #dddddd;
            box-shadow: 5px 5px 20px #aaa;

            margin-left: auto;
            margin-right: auto;
            margin-top: 100px;
            padding: 20px 40px;
        }

        .account h2 {
            margin-top: 10px;
            text-align: center;
        }
    </style>
</head>
<body>
<div class="account">
    <h2>用戶登入</h2>
    <form method="post" novalidate>
        {% csrf_token %}
        <div class="form-group">
            <label>用戶名</label>
            {{ form.username }}
            <span style="color: red;">{{ form.username.errors.0 }}</span>
        </div>
        <div class="form-group">
            <label>密碼</label>
            {{ form.password }}
            <span style="color: red;">{{ form.password.errors.0 }}</span>
        </div>
        <div class="form-group">
            <label for="id_code">圖片驗證碼</label>
            <div class="row">
                <div class="col-xs-7">
                    {{ form.code }}
                    <span style="color: red;">{{ form.code.errors.0 }}</span>
                </div>
                <div class="col-xs-5">
                    <img id="image_code" src="/image/code/" style="width: 125px;">
                </div>
            </div>
        </div>
        <input type="submit" value="登入" class="btn btn-primary">
    </form>
</div>
</body>
</html>

app01/templates/pretty_add.html
{% extends 'layout.html' %}

{% block content %}
<div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">新建用戶</h3>
            </div>
            <div class="panel-body">
                {#                套版：https://v3.bootcss.com/css/#forms#}
                <form method="post" novalidate>
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color: red">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-default">提 交</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

app01/templates/pretty_edit.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">編輯靓號</h3>
            </div>
            <div class="panel-body">
                {#                套版：https://v3.bootcss.com/css/#forms#}
                <form method="post" novalidate>
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color: red">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-default">提 交</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

app01/templates/pretty_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div style="margin-bottom: 10px" class="clearfix">
            <a class="btn btn-success" href="/pretty/add/">
                <span class="glyphicon glyphicon-circle-arrow-right" aria-hidden="true"></span>
                新建手機號
            </a>
            <div style="float: right;width: 300px">
                <form method="get">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="{{ search_data }}"
                               value="{{ search_data }}">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="submit">
                                <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                            </button>
                        </span>
                    </div>
                </form>
            </div>
        </div>
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                用戶列表
            </div>

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>號碼</th>
                    <th>價格</th>
                    <th>級別</th>
                    <th>狀態</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for user in queryset %}
                    <tr>
                        <th>{{ user.id }}</th>
                        <td>{{ user.mobile }}</td>
                        <td>{{ user.price }}</td>
                        <td>{{ user.get_level_display }}</td>
                        <td>{{ user.get_status_display }}</td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="/pretty/edit/{{ user.id }}">編輯</a>
                            <a class="btn btn-danger btn-xs" href="/pretty/del/{{ user.id }}">刪除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="clearfix">
            <ul class="pagination">
                {{ page_string }}

            </ul>
        </div>
    </div>
{% endblock %}

app01/templates/user_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div style="margin-bottom: 10px">
            <a class="btn btn-success" href="/user/add">
                <span class="glyphicon glyphicon-circle-arrow-right" aria-hidden="true"></span>
                新建用戶
            </a>
            <a class="btn btn-success" href="/user/model/form/add">
                <span class="glyphicon glyphicon-circle-arrow-right" aria-hidden="true"></span>
                新建form用戶
            </a>
        </div>
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                用戶列表
            </div>

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>用戶名稱</th>
                    <th>密碼</th>
                    <th>age</th>
                    <th>餘額</th>
                    <th>入職時間</th>
                    <th>性別</th>
                    <th>部門</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for user in user_list %}
                    <tr>
                        <th>{{ user.id }}</th>
                        <td>{{ user.name }}</td>
                        <td>{{ user.password }}</td>
                        <td>{{ user.age }}</td>
                        <td>{{ user.account }}</td>
                        <td>{{ user.create_time|date:"Y-m-d" }}</td>
                        <td>{{ user.get_gender_display }}</td>
                        <td>{{ user.depart.title }}</td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="/user/edit/{{ user.id }}">編輯</a>
                            <a class="btn btn-danger btn-xs" href="/user/del/{{ user.id }}">刪除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="clearfix">
            <ul class="pagination">
                {{ page_string }}

            </ul>
        </div>
    </div>
{% endblock %}

app01/templates/user_model_form_add.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'bootstrap-datepicker-1.9.0-dist/css/bootstrap-datepicker.min.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">新建用戶</h3>
            </div>
            <div class="panel-body">
                {#                套版：https://v3.bootcss.com/css/#forms#}
                <form method="post" novalidate>
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color: red">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-default">提 交</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}


{% block js %}
    <script src="{% static 'bootstrap-datepicker-1.9.0-dist/js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'bootstrap-datepicker-1.9.0-dist/locales/bootstrap-datepicker.zh-TW.min.js' %}"></script>
    <script>
        $(function (){
            $('#id_create_time').datepicker({
                format: 'yyyy-mm-dd',
                startDate: '0',
                language: "zh-TW",
                autoclose: true
            });
        })
    </script>
{% endblock %}